[phases.setup]
nixPkgs = ['nodejs', 'coreutils', 'typescript']
aptPkgs = ['python3', 'make', 'g++']

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "chmod +x ./node_modules/.bin/tsc",
  "./node_modules/.bin/tsc"
]

[phases.start]
cmd = "node dist/index.js"
